// NOTE auxiliary typeface
const monospace = [
  '"JetBrains Mono"',
  '"Lucida Console"',
  'Courier',
  'monospace',
].join(',')

const typography = {
  fontFamily: [
    'Inter',
    'Geist',
    '-apple-system',
    'BlinkMacSystemFont',
    '"Segoe UI"',
    'Roboto',
    'Helvetica',
    'Arial',
    'sans-serif',
  ].join(','),
  fontSize: 14,
  monospace1: {
    fontFamily: monospace,
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '150%',
    letterSpacing: 0.15,
  },
  monospace2: {
    fontFamily: monospace,
    fontSize: 13,
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '143%',
    letterSpacing: 0.15,
  },
  h1: {
    fontSize: 40,
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '112%',
    letterSpacing: 0,
  },
  h2: {
    fontSize: 32,
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '120%',
    letterSpacing: 0,
  },
  h3: {
    fontSize: 28,
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '124%',
    letterSpacing: 0,
  },
  h4: {
    fontSize: 24,
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '130%',
    letterSpacing: 0,
  },
  h5: {
    fontSize: 22,
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '132%',
    letterSpacing: 0,
  },
  h6: {
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '140%',
    letterSpacing: 0,
  },
  subtitle1: {
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '150%',
    letterSpacing: 0,
  },
  subtitle2: {
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '145%',
    letterSpacing: 0,
  },
  body1: {
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '155%',
    letterSpacing: 0,
  },
  body2: {
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '150%',
    letterSpacing: 0,
  },
  // NOTE 🆕 custom variant
  buttonLarge: {
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '26px',
    letterSpacing: 0,
    textTransform: 'none',
  },
  button: {
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '24px',
    letterSpacing: 0,
    textTransform: 'none',
  },
  // NOTE 🆕 custom variant
  buttonSmall: {
    fontSize: 13,
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '22px',
    letterSpacing: 0,
    textTransform: 'none',
  },
  caption: {
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '144%',
    letterSpacing: 0,
  },
  overline: {
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '120%',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  // NOTE 🆕 custom variants (from here on)
  avatarLetter: {
    fontSize: 20,
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '20px',
    letterSpacing: 0.14,
  },
  inputLabel: {
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '12px',
    letterSpacing: 0.15,
  },
  helperText: {
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '20px',
    letterSpacing: 0.4,
  },
  inputText: {
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '24px',
    letterSpacing: 0.15,
  },
  tooltip: {
    fontSize: 10,
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '14px',
  },
}

export default typography
