import type { DemoGuideContent } from '../types'
import data from './compoundInterest.data.json'

// Captured from a real generation on 2026-08-01. The JSON is generated by
// scripts/build-demo-guide.mjs and must be regenerated, never hand-edited.
const compoundInterest: DemoGuideContent = {
  ...(data as Omit<DemoGuideContent, 'chat'>),
  chat: [
    {
      id: 'q1',
      chip: 'Can I catch up like at the gym?',
      question:
        "If I take three months off training I can come back and push harder to make it up. Why doesn't that work with compounding?",
      answer: [
        'Because the two systems reward different inputs. In training, the adaptation follows the work you put in — push harder and the body responds. The guide leans on exactly that when it calls an early contribution a training adaptation that has had more time to build, and regular deposits a run of consistent workouts.',
        'Money breaks the analogy in one specific place: the return is not a predictable strength increase you can force with effort. What a missed year costs you is time on the balance, and working harder later does not buy that time back. It only adds more principal, which then has fewer periods left to compound.',
        'The guide is careful not to overclaim here. A later saver can genuinely end up ahead by contributing enough, earning a higher return, or saving for longer. What it rules out is the assumption that adding a little more effort later automatically repairs the skipped years.',
        'So the gym instinct is half right. The part that transfers is consistency — pick a load you can actually sustain and keep showing up. The money version of that is automating a manageable contribution so it stops depending on motivation.',
      ].join('\n\n'),
    },
    {
      id: 'q2',
      chip: 'Pay off debt or start investing?',
      question:
        'I have a credit card balance and I want to start investing. Should I do both at once, or clear the debt first?',
      answer: [
        "The guide's order of operations puts that debt ahead of investing, and the reason is mechanical rather than moral: compounding runs in both directions.",
        'Its sequence is cash flow and an emergency reserve appropriate to your situation, then high-interest debt, then employer matches or tax-advantaged accounts where those apply — checking their rules and fees before committing.',
        'High-interest debt comes first because its cost may exceed a realistic investment return. It is the engine from the first lesson running against you: interest added to an unpaid balance becomes part of the base the next interest is calculated on, the same way reinvested gains do when the engine is on your side.',
        'Two details worth keeping. It says high-interest debt specifically, not every debt you hold. And the reserve sits ahead of both, because its job is to stop the next surprise turning into new debt while you are trying to invest. What actually fits you depends on your circumstances and the account rules and tax treatment where you live.',
      ].join('\n\n'),
    },
    {
      id: 'q3',
      chip: 'What return should I assume?',
      question:
        'The examples use 7% and 6%. What number should I actually put in when I model my own plan?',
      answer: [
        'Not a single number — that is the point the guide keeps returning to. The 7% in the early-saver comparison and the 6% in the $150-a-month example are described as hypothetical on purpose, and the balances they produce are called illustrations, not forecasts.',
        'What it asks for instead is a range. Run the same plan with a lower and a higher return, with a smaller and a larger contribution, with fees included, and over a shorter time period. If the plan only survives at the optimistic end of that range, you have learned something useful about the plan.',
        'Two adjustments people leave out:',
        '- **Fees**, because they reduce the amount that stays invested and so shrink the base every later return builds on.\n- **Inflation**, because a return stated before inflation is not future spending power. The $69,300 in the annuity example is explicitly before fees, taxes, and inflation.',
        'It also helps to remember that whatever rate you type in is an average, not a schedule. Returns can be negative, uneven, or lower than expected, so treat the result as an estimate under stated assumptions rather than a projection you can plan around to the dollar.',
      ].join('\n\n'),
    },
  ],
}

export default compoundInterest
