import type { DemoGuideContent } from '../types'
import data from './immuneResponse.data.json'

// Captured from a real generation on 2026-08-02. The JSON is generated by
// scripts/build-demo-guide.mjs and must be regenerated, never hand-edited.
const immuneResponse: DemoGuideContent = {
  ...(data as Omit<DemoGuideContent, 'chat'>),
  chat: [
    {
      id: 'q1',
      chip: 'Where does the airport analogy break?',
      question:
        'The airport comparison only shows up in the last section, and it says the body is unlike an airport. Where does the comparison actually stop working?',
      answer: [
        'It holds for the shape of the system and stops at what happens after the incident. Entrances and screening rules, rapid responders handling suspicious activity, specialists trained for a particular threat — that layering is real, and it is the useful part.',
        'The first difference is what gets checked. Airport screening compares you against something already known. Your early defenses do not: tissue cells use pattern-recognition receptors that read common molecular patterns found on microbes or released by damaged cells, so a microbe your body has never met still trips the alarm. There is no list to be on.',
        'The second is that the specialists are not on shift. A lymphocyte responds only when its receptor and the activation signals fit an antigen that a dendritic cell has carried to a nearby lymph node, and even then it has to multiply into a population large enough to matter. The specialist team is assembled after the incident starts, not called down from an office upstairs.',
        'The third is the one the guide names itself: the body must operate inside living tissue, so identification, removal, repair, and restraint happen together. Inflammation that contains a microbe can also injure healthy tissue if it becomes excessive or prolonged, and an airport never has to rebuild the concourse its own response damaged. Winding the response down is not an off switch either — regulatory signals and the removal of activated cells bring it back while macrophages clear the debris.',
      ].join('\n\n'),
    },
    {
      id: 'q2',
      chip: 'Should I let a fever run?',
      question:
        'The guide says a fever can help. Does that mean I should leave one alone and let it do its work?',
      answer: [
        'The guide deliberately does not go that far. It says a fever can make the body less favorable to some microbes and support immune activity — some, not all — and in the same breath that a high or persistent fever can be dangerous.',
        'So fever is described as two-sided, not as good. Nothing on these pages gives you a threshold, a duration, or a view on treating one, and the only instruction it does commit to is the practical one: worsening or severe symptoms need medical assessment.',
        "The more useful idea sits underneath it. Symptoms reflect both the infection and the body's response, so how rough you feel is not a clean readout of how much microbe is present. The redness, warmth, swelling and pain around an infected cut are your own vessels becoming more permeable so that fluid and defensive proteins can reach the tissue. That is the response, not the bacterium.",
        'It is the same reason the last page separates recovery from clearance. Fatigue, pain and appetite can take time to normalize even after the microbe is gone, and lingering symptoms do not always mean an infection is still running. That is a reason to expect a slow tail — not a reason to wait out something that is getting worse.',
      ].join('\n\n'),
    },
    {
      id: 'q3',
      chip: 'Why does the specific response take days?',
      question:
        'Page one says the fast defenses are buying time while the adaptive response develops. What is actually taking so long?',
      answer: [
        'Three things have to finish before a targeted attack exists, and none of them can be skipped.',
        'The information has to travel first. Detection happens out in the tissue, but activation does not: some activated dendritic cells collect material from the microbe and carry it to a nearby lymph node, where they display small fragments — antigens — on surface molecules.',
        "Then the right cell has to be found. A lymphocyte responds only when its receptor and the activation signals fit the presented antigen. That requirement is the guide's explanation for why the system does not misfire constantly, but it also means nothing targeted exists until a matching cell has been located and switched on.",
        'Then it has to be scaled. A matched lymphocyte multiplies into a larger population aimed at the same target, and the B cells among them become plasma cells that release antibodies. One matching cell is not a defense; a population is.',
        'Which is exactly what the fast side is for. Inflammation, neutrophils, macrophages and complement all contribute to clearing an infection, but the job the guide credits them with in those first days is narrower: slowing the spread, and creating the time the three steps above need. Both halves are running the whole time; only one of them is ready on day one.',
      ].join('\n\n'),
      answerDelayMs: 1800,
    },
  ],
}

export default immuneResponse
