import type { DemoGuideContent } from '../types'
import data from './learningBottlenecks.data.json'

// Captured from a real generation on 2026-08-02. The JSON is generated by
// scripts/build-demo-guide.mjs and must be regenerated, never hand-edited.
const learningBottlenecks: DemoGuideContent = {
  ...(data as Omit<DemoGuideContent, 'chat'>),
  chat: [
    {
      id: 'q1',
      chip: 'How do I see my own queue?',
      question:
        'In a kitchen the bottleneck is visible: tickets pile up and the pass backs up. My own studying never shows me anything. How do I actually see where my slow station is?',
      answer: [
        'A kitchen has one advantage over you: it fails in public. Learning fails quietly, so the signals have to be created on purpose rather than waited for.',
        'You are looking for three shapes. A **queue** is unfinished material accumulating, the chapters and problem sets and saved videos you never got through. **Rework** is studying the same material again and again without stronger performance. A **stoppage** is the point where you cannot continue without external help. They come from different causes, so the shape you find already narrows the diagnosis.',
        'To make them show up, remove the support. Timed attempts, recall without notes, error patterns, completed practice, and feedback from someone who knows the subject are observable. Boredom and confidence are real, but they will not tell you which station is slow.',
        'Then write it down. A log with date, task, score or quality rating, main error type, help used, and next adjustment is your ticket rail: after a handful of entries the pattern sits on the page instead of in your memory of how the sessions felt.',
      ].join('\n\n'),
    },
    {
      id: 'q2',
      chip: 'Which candidate do I test first?',
      question:
        'I listed five candidates and three of them look equally plausible. How do I choose which one to test first without burning a month on the wrong guess?',
      answer: [
        'Rank them with the two questions: how strongly does each candidate actually appear in your evidence, and how much would fixing it improve the target outcome? A weakness you feel guilty about but cannot point to in a timed attempt or an error pattern drops down the list on the first question alone.',
        'Then stop trying to be right and start being testable. Take the top candidate, change only that condition for a short period, and record the task, your initial performance, the intervention, and the result. Five problems without notes, study only the error pattern, five similar problems later is enough to interpret.',
        'The result re-ranks the list for you. Improvement supports the diagnosis, though one result is not proof. Nothing changing is information too: revise the diagnosis or make the intervention more precise, then move to the next candidate.',
        'The one thing worth protecting is the single variable. Change resource, task type, and timing at the same time and you may improve without knowing why, which leaves you unable to repeat it.',
      ].join('\n\n'),
    },
    {
      id: 'q3',
      chip: 'Did the fix actually work?',
      question:
        'After a couple of weeks of closed-book recall the material feels much easier. How do I tell whether I fixed the constraint or just got comfortable with my own practice?',
      answer: [
        "Familiar ease is the weakest evidence available. A skill is not improved simply because yesterday's exercise felt easier, because that exercise is the thing you have been rehearsing.",
        'Verify with a task that resembles the real goal but is not identical to what you practised, and check four things: accuracy, independence, speed where it matters, and retention after a delay. Compare it against the baseline you recorded before the fix. Without a baseline you are comparing against a feeling.',
        'Keep the change if independent performance is better and retention is reasonable. Replace it if results stay flat despite faithful use, or if it improves the narrow drill while the actual goal does not move. Judge it after enough repetitions to see a pattern, not after one uncomfortable session.',
        'If it did work, expect a new limit to appear: clearing one station tends to expose a delay at the pass. That is the system behaving normally, not a sign that the first diagnosis was wasted.',
      ].join('\n\n'),
    },
  ],
}

export default learningBottlenecks
