import type { DemoGuideContent } from '../types'
import data from './whyYouForget.data.json'

// Captured from a real generation on 2026-08-02. The JSON is generated by
// scripts/build-demo-guide.mjs and must be regenerated, never hand-edited.
const whyYouForget: DemoGuideContent = {
  ...(data as Omit<DemoGuideContent, 'chat'>),
  chat: [
    {
      id: 'q1',
      chip: 'Should I wait until I forget?',
      question:
        'The guide says forgetting is part of the process. Does that mean I should deliberately wait until I have forgotten something before reviewing it?',
      answer:
        'Not quite. The aim is to make recall effortful while it is still possible, not to lose the memory first.\n\nDifficulty has to stay manageable. A short delay makes recall effortful, and that effort strengthens later access when you get feedback and correct the error. But if you wait until nothing comes back at all, you are left guessing randomly, and random guessing does not build accurate connections the way reviewing a clear answer and trying again does.\n\nWaiting too long is not a disaster, though. A failed recall is real feedback: it tells you the item was more fragile than you assumed. It just costs you a corrective review, which is exactly why the interval should follow performance instead of a fixed timetable.\n\nSo in practice: push the delay out when an item comes back accurate and relaxed, and pull it back in when errors recur. Spacing uses a controlled amount of forgetting, not as much as you can stand.',
    },
    {
      id: 'q2',
      chip: "Isn't daily practice already spacing?",
      question:
        'I already play through my pieces most days. Is that not already spaced repetition?',
      answer:
        'Partly. Returning to a passage across separate sessions is genuine spacing, and instrument practice contains it naturally. What daily playing usually misses is the retrieval half.\n\nIf the score is in front of you, you are mostly recognizing: the notes look familiar and your hands follow. That is the same trap as rereading a definition. Retrieval means performing the passage with the notation hidden, and it is more demanding because nothing on the page is cueing you.\n\nFull run-throughs hide the problem too. Familiar transitions carry you forward, so a weak bar can survive weeks of daily playing without ever being tested on its own.\n\nTwo changes turn a daily habit into deliberate spacing. First, pick specific targets rather than whole pieces: a fingering pattern, a rhythm, a chord progression, a phrase beginning. Second, move the check away from the repetition that produced it, so you test after a warm-up, after another piece, or near the end of the session rather than straight after the work that made it smooth.',
    },
    {
      id: 'q3',
      chip: 'What if it keeps failing?',
      question:
        'What should I do with something that keeps failing no matter how often I come back to it?',
      answer:
        'Repeated failure usually means the target is too big, not that you need more reviews.\n\nThe flashcard rule applies here as well: one clear prompt, one concise answer. If the prompt is really asking for a whole chapter, or a whole page of music, a failure does not tell you which part broke, so each review repairs nothing in particular.\n\nDiagnose before you reschedule. Attempt it, check it against the source or the score, and name the exact detail that was missing. Something like "accurate after two days, rhythm uncertain" is a note you can act on. "Still cannot do it" is not.\n\nThen split it. Mark the difficult location, practice it on its own, and reconnect it to the nearby material so the skill transfers back into context. Keep the delay short while it is fragile and only stretch it out once it comes back accurate and relaxed.\n\nOne thing to watch: do not keep repeating the mistake at speed. The error can become the strongest pattern you retrieve. Slow down enough to clarify the coordination, then restore the intended tempo gradually.',
    },
  ],
}

export default whyYouForget
